-- Make the handle_new_user function idempotent by using CREATE OR REPLACE
-- and secure it by setting the search_path.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name)
  VALUES (new.id, new.raw_user_meta_data->>'full_name');
  RETURN new;
END;
$$;

-- Drop the trigger if it exists, then recreate it.
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Drop and recreate policies for profiles to ensure they are correct and avoid conflicts.
DROP POLICY IF EXISTS "Users can view their own profile." ON public.profiles;
CREATE POLICY "Users can view their own profile." ON public.profiles
  FOR SELECT USING (auth.uid() = id);

DROP POLICY IF EXISTS "Users can insert their own profile." ON public.profiles;
CREATE POLICY "Users can insert their own profile." ON public.profiles
  FOR INSERT WITH CHECK (auth.uid() = id);
  
DROP POLICY IF EXISTS "Users can update their own profile." ON public.profiles;
CREATE POLICY "Users can update their own profile." ON public.profiles
  FOR UPDATE USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

-- Create the workflow_runs table if it doesn't already exist.
CREATE TABLE IF NOT EXISTS public.workflow_runs (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    user_id uuid references auth.users(id) on delete cascade not null,
    workflow_title text not null
);

-- Enable RLS for the new table.
ALTER TABLE public.workflow_runs ENABLE ROW LEVEL SECURITY;

-- Add policies for the new workflow_runs table.
DROP POLICY IF EXISTS "Users can view their own workflow runs." ON public.workflow_runs;
CREATE POLICY "Users can view their own workflow runs." ON public.workflow_runs
  FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert their own workflow runs." ON public.workflow_runs;
CREATE POLICY "Users can insert their own workflow runs." ON public.workflow_runs
  FOR INSERT WITH CHECK (auth.uid() = user_id);
